### ISSUE TITLE
Publish releases aligned with Docker image versions

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/openAFRICA#23]
## Description
We currently create Docker images that are versioned as part of the development process for openAFRICA, we should also align these with releases created here.

## Tasks

- [ ] Improve Docker image creation documentation
- [ ] Add release process in documentation
- [ ] Add a changelog
- [ ] Create first release
